version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - ml-model
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./ml-model
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development
