name: Build and Test Docker Compose

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Docker Compose Build
      run: docker-compose build

    - name: Docker Compose Up (Test)
      run: docker-compose up -d

    - name: Test Backend API
      run: |
        sleep 10
        curl http://localhost:5000/flask/recommend || echo "Backend not responding"
