name: Build and Test Docker Compose

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Images
      run: docker-compose build

    - name: Start Docker Containers
      run: docker-compose up -d

    - name: Wait for Backend to be Ready
      run: |
        echo "Waiting for backend..."
        for i in {1..10}; do
          curl http://localhost:5000/flask/recommend && break
          echo "Retry $i: Backend not ready yet..."
          sleep 5
        done

    - name: Show Running Containers (Debug)
      run: docker ps

    - name: Stop Docker Containers
      run: docker-compose down
